<?php

/**
 * @file
 * Contains tonner.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tonner_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the tonner module.
        case 'help.page.tonner':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('News and Tonner generator') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function tonner_theme() {
    return [
        'tonner' => [
            'template' => 'tonner',
            'render element' => 'children',
            'variables'=>['total_headlines'=> null,'tonescollect'=>null,'searchform'=>null,'graphheadline'=>null,'topicsCloud'=>null]
        ],
        'tonneroverview' => [
          'template' => 'tonneroverview',
          'render element' => 'children',
          'variables'=>['data'=> null]
        ],
    ];
}
